### ISSUE TITLE
大佬评论推荐使用这个 感觉比你现在用的那个编辑器更好

### ISSUE THREAD

**Issue by Yakumo-Yukari** [zhaoyangkun/aries#14]
https://github.com/imaegoo/twikoo

感觉用户评论编辑器使用vditor有点多余了

**Comment by zhaoyangkun** [comment]
好的，我去试试看

**Comment by zhaoyangkun** [comment]
大概了解了下这个评论组件，感觉部署起来有些麻烦，aries自带的评论组件确实臃肿了一些。

**Comment by zhaoyangkun** [comment]
> https://github.com/imaegoo/twikoo
> 
> 感觉用户评论编辑器使用vditor有点多余了

大概了解了下这个评论组件，感觉部署起来有些麻烦，aries自带的评论组件确实臃肿了一些。

**Comment by zhaoyangkun** [comment]
我在测试 twikoo，给了一个折中的方案：在后台管理里加个选项，可以自主选择评论组件，**本地评论组件**或者**twikoo评论组件**。

**Comment by Yakumo-Yukari** [comment]
> 我在测试 twikoo，给了一个折中的方案：在后台管理里加个选项，可以自主选择评论组件，**本地评论组件**或者**twikoo评论组件**。

![q](https://user-images.githubusercontent.com/12076232/150670992-51f08761-ee23-43f6-8b14-a86e747d8a0e.PNG)

大佬 现在评论成功后不会清除内容刷新页面，如果一直点提交 会一直提交成功

**Comment by zhaoyangkun** [comment]
> 
评论默认开启了审核功能，只有审核通过了才能显示。其实我本来想加一个验证码功能的，来防止恶意评论。网站为必填字段确实没考虑到位，后期会处理一下。

**Comment by zhaoyangkun** [comment]
> > 我在测试 twikoo，给了一个折中的方案：在后台管理里加个选项，可以自主选择评论组件，**本地评论组件**或者**twikoo评论组件**。
> 
> ![q](https://user-images.githubusercontent.com/12076232/150670992-51f08761-ee23-43f6-8b14-a86e747d8a0e.PNG)
> 
> 大佬 现在评论成功后不会清除内容刷新页面，如果一直点提交 会一直提交成功，还有就是 网址不应该设置为必填内容 因为评论的人不一定有网站

还有其他问题的话，直接加我qq 2295098032联系吧，
