### ISSUE TITLE
大佬 请教下 如果要实现 加密博文要怎么实现

### ISSUE THREAD

**Issue by Yakumo-Yukari** [zhaoyangkun/aries#15]
我看有的博客  一些文章需要输入密码  才能阅读  这种是怎么实现的

**Comment by zhaoyangkun** [comment]
类似于登录，每次访问加密文章时，先从缓存中读取密码，若缓存中不存在密码，提示输入密码，再进行密码校验；若缓存中存在密码，直接取出密码进行密码校验。

**Comment by Yakumo-Yukari** [comment]
> 类似于登录，每次访问加密文章时，先从缓存中读取密码，若缓存中不存在密码，提示输入密码，再进行密码校验；若缓存中存在密码，直接取出密码进行密码校验。

  谢谢
