### ISSUE TITLE
静态文件源无法访问

### ISSUE THREAD

**Issue by liuyuede123** [zhaoyangkun/aries#29]
![image](https://user-images.githubusercontent.com/11690339/180376444-dafd352b-6f2b-4f88-8ad0-9d9e225ed1f2.png)
![image](https://user-images.githubusercontent.com/11690339/180376504-3bfa5830-31ea-4849-a1c0-84084477f7c9.png)
修改后的这个源无法访问，导致后台文章没法编辑😂

**Comment by zhaoyangkun** [comment]
在处理了，请更新下docker镜像
