### ISSUE TITLE
如何正确配置上海时区

### ISSUE THREAD

**Issue by thetrueself** [zhaoyangkun/aries#32]
1. 时区设置成`Asia/Shanghai`，提示以下错误：
`数据库连接错误：invalid DSN: did you forget to escape a param value?
panic: 数据库连接错误：invalid DSN: did you forget to escape a param value?
`
2. 时区设置成`Asia Shanghai`，提示以下错误：
`数据库连接错误：unknown time zone Asia Shanghai
panic: 数据库连接错误：unknown time zone Asia Shanghai
`
3. 时区设置成`+8:00`，提示以下错误：
`
数据库连接错误：unknown time zone  8:00
panic: 数据库连接错误：unknown time zone  8:00
`

**Comment by zhaoyangkun** [comment]
很抱歉，该部分代码存在问题，我会在下一个版本中修复。

出现问题的原因为：`gorm` 设置 `mysql` 时区参数 `loc` 的值时需进行 `UrlEncode`。

解决办法为：对时区参数 `loc` 的值进行 Url 编码，需要手动修改项目路径下的 `config/db/db.go` 中的相关代码：

```go
import "net/url"

// 获取数据库连接
func getDataSource() string {
	dataSource := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=true&loc=%s",
		setting.Config.Database.UserName,
		setting.Config.Database.Password,
		setting.Config.Database.Host,
		setting.Config.Database.Port,
		setting.Config.Database.Database,
		url.QueryEscape(setting.Config.Database.TimeZone), // 对时区进行 Url 编码
	)
	return dataSource
}
```

**Comment by zhaoyangkun** [comment]
修改完代码之后，在 `develop.yaml` 配置文件中将时区 `timezone` 设置为 `Asia/Shanghai` 即可。
