### ISSUE TITLE
关于后台系统的一些问题

### ISSUE THREAD

**Issue by limits220284** [zhaoyangkun/aries#47]
您好！您所写的通过docker部署网站，但是并没有发现关于这个后台登录系统的部署，请问这部分是怎么回事呢？感谢您的回答

**Comment by zhaoyangkun** [comment]
整个后台管理系统（包括登录系统）是使用 Vue 实现的，已经打包到项目根路径的 `resources/admin` 目录下，部署时候会在 Go 服务器中加载 `resources/admin` 目录的静态文件。
