### ISSUE TITLE
请问 博客主页显示有问题怎么回事

### ISSUE THREAD

**Issue by Kirby980** [zhaoyangkun/aries#53]
<img width="780" alt="image" src="https://github.com/zhaoyangkun/aries/assets/156735257/2c290fcb-2334-4555-9f91-1d85bc93cb51">/
请问 博客主页显示有问题怎么回事

**Comment by zhaoyangkun** [comment]
> <img alt="image" width="780" src="https://private-user-images.githubusercontent.com/156735257/306549030-2c290fcb-2334-4555-9f91-1d85bc93cb51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTE4NTUsIm5iZiI6MTcwODc1MTU1NSwicGF0aCI6Ii8xNTY3MzUyNTcvMzA2NTQ5MDMwLTJjMjkwZmNiLTIzMzQtNDU1NS05ZjkxLTFkODViYzkzY2I1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwNTEyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWM2NzhmOThiODNmMTIzZTBmM2RmNDQ4MmM0YmExMWY3MzQzODI5YTU4ZDlmNjYxZDA4MWRlMDMzMjcxZWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7ABFBn3b3c8nYJdR3lcEUZQQpqavEyXutsnKs-FXFLc">/ 请问 博客主页显示有问题怎么回事

应该是**静态文件根路径**设置得不正确，可以进入博客后台`管理`->`系统`->`设置`，检查下**静态文件根路径**，本地测试环境下，**静态文件根路径**需要和**网站地址**保持一致。
![image](https://github.com/zhaoyangkun/aries/assets/29301950/cc71f58d-fb7a-4635-9103-04df49f638eb)

**Comment by Kirby980** [comment]
<img width="1440" alt="image" src="https://github.com/zhaoyangkun/aries/assets/156735257/111911ff-6357-40ad-a516-00df71e1b93a">
<img width="1419" alt="image" src="https://github.com/zhaoyangkun/aries/assets/156735257/4daaa6d7-47f3-409d-9188-4517b4b8df3c">
主页的log 没显示了
