### ISSUE TITLE
本地评论有问题

### ISSUE THREAD

**Issue by Kirby980** [zhaoyangkun/aries#55]
<img width="1380" alt="image" src="https://github.com/zhaoyangkun/aries/assets/156735257/f5a29830-2e98-4c57-8456-938a79f0dbf3">

**Comment by Kirby980** [comment]
上传图片也有问题
<img width="1218" alt="image" src="https://github.com/zhaoyangkun/aries/assets/156735257/6724b689-f2a6-4b8a-af87-cf2fb3f5c3b7">

**Comment by zhaoyangkun** [comment]
> 上传图片也有问题 <img alt="image" width="1218" src="https://private-user-images.githubusercontent.com/156735257/310349475-6724b689-f2a6-4b8a-af87-cf2fb3f5c3b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTI1NDgsIm5iZiI6MTcwOTg5MjI0OCwicGF0aCI6Ii8xNTY3MzUyNTcvMzEwMzQ5NDc1LTY3MjRiNjg5LWYyYTYtNGI4YS1hZjg3LWNmMmZiM2Y1YzNiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMDA0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWU1NTI5MzRlNjUzYmNiOGM4NzI3ZGNhODg2MjQ3ODhhODRhY2RjNWJiNTgzNDVlYTU3MzI5YWFiNTgyNzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b4Wg3Vl_5_ECJ_UWgtYnlM1WwG4YbSXqqAnviagui7Q">

能给一下Go服务器那边的错误日志吗

**Comment by zhaoyangkun** [comment]
> <img alt="image" width="1380" src="https://private-user-images.githubusercontent.com/156735257/310348412-f5a29830-2e98-4c57-8456-938a79f0dbf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTI2MDQsIm5iZiI6MTcwOTg5MjMwNCwicGF0aCI6Ii8xNTY3MzUyNTcvMzEwMzQ4NDEyLWY1YTI5ODMwLTJlOTgtNGM1Ny04NDU2LTkzOGE3OWYwZGJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMDA1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmVkNzgxMTY3YjQ0YjkzNGRiYmM2YzU1NWQzMjJjMzFkNjM3ZTMwMjY5YTFjOGEyYjg4OGVhYzk3MmJkYWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.loQGWkBjTjWB_BqPanrGU0RXpA7pW7sgs9sItKwiEYQ">

本地评论功能不建议使用，我之前测试是可以的，你拉下最新版的代码试试

**Comment by zhaoyangkun** [comment]
- 上传图片失败，可能是图床网络不稳定，建议不要使用 `SM.MS` 和 `ImgBB` 图床。
- 目前已将图片上传功能（除`腾讯COS`外）从服务器端上传修改为前端直传，新增了 `PicUI` 图床上传功能，不再受限于服务器带宽限制，上传图片速度有较大提升。
- 本地评论功能的 Bug 已修复，是由于 `Vditor CDN` 路径错误导致的，请拉取下最新的代码再运行试试。
